
version: 2

models:
    - name: partition
      description: "A starter dbt model"
      columns:
          - name: _id
            description: "The primary key for this table"
            tests:
                - unique
