SELECT COALESCE((regexp_split_to_array(doc #>> '{fields,geolocation}'::text[], ' '::text))[1], doc #>> '{fields,location,lat}'::text[]) AS "inputs/meta/location/lat",
   COALESCE((regexp_split_to_array(doc #>> '{fields,geolocation}'::text[], ' '::text))[2], doc #>> '{fields,location,long}'::text[]) AS "inputs/meta/location/long",
   doc #>> '{fields,inputs,source}'::text[] AS "inputs/source",
   doc #>> '{fields,inputs,source_id}'::text[] AS "inputs/source_id",
   doc #>> '{fields,inputs,t_follow_up_type}'::text[] AS "inputs/t_follow_up_type",
   doc #>> '{fields,inputs,t_follow_up_count}'::text[] AS "inputs/t_follow_up_count",
   COALESCE(doc #>> '{fields,inputs,contact,_id}'::text[], patient.doc ->> '_id'::text) AS "inputs/contact/_id",
   COALESCE(doc #>> '{fields,inputs,contact,name}'::text[], patient.doc ->> 'name'::text) AS "inputs/contact/name",
   COALESCE(doc #>> '{fields,inputs,contact,date_of_birth}'::text[], patient.doc ->> 'date_of_birth'::text) AS "inputs/contact/date_of_birth",
   doc #>> '{fields,inputs,contact,parent,contact,phone}'::text[] AS "inputs/contact/parent/contact/phone",
   doc #>> '{fields,patient_contact_phone}'::text[] AS patient_contact_phone,
   COALESCE(doc #>> '{fields,inputs,contact,_id}'::text[], patient.doc ->> '_id'::text) AS patient_id,
   COALESCE(doc #>> '{fields,inputs,contact,name}'::text[], patient.doc ->> 'name'::text) AS patient_name,
   doc #>> '{fields,referral_follow_up_needed}'::text[] AS referral_follow_up_needed,
   doc #>> '{fields,follow_up_count}'::text[] AS follow_up_count,
   doc #>> '{fields,danger_signs}'::text[] AS danger_signs,
   doc #>> '{fields,patient_improved}'::text[] AS patient_improved,
   doc #>> '{fields,patient_better}'::text[] AS patient_better,
   doc #>> '{fields,patient_health_facility_visit}'::text[] AS patient_health_facility_visit,
   doc #>> '{fields,patient_age_in_days}'::text[] AS patient_age_in_days,
   doc #>> '{fields,patient_age_in_years}'::text[] AS patient_age_in_years,
   doc #>> '{fields,patient_age_in_months}'::text[] AS patient_age_in_months,
   doc #>> '{fields,form_source_id}'::text[] AS form_source_id,
   doc #>> '{fields,p_note}'::text[] AS p_note,
   doc #>> '{fields,group_followup_options,follow_up_type}'::text[] AS follow_up_type,
   doc #>> '{fields,group_followup_options,follow_up_method}'::text[] AS follow_up_method,
   doc #>> '{fields,group_followup_options,call_button1}'::text[] AS call_button1,
   doc #>> '{fields,group_followup_options,call_button2}'::text[] AS call_button2,
   doc #>> '{fields,group_danger_signs,danger_signs_note}'::text[] AS danger_signs_note,
   doc #>> '{fields,group_danger_signs,g_danger_signs}'::text[] AS g_danger_signs,
   doc #>> '{fields,group_danger_signs,danger_signs_referral}'::text[] AS danger_signs_referral,
   doc #>> '{fields,group_improved,g_patient_treatment_outcome}'::text[] AS g_patient_treatment_outcome,
   doc #>> '{fields,group_improved,g_patient_improved}'::text[] AS g_patient_improved,
   doc #>> '{fields,group_improved,patient_improved_yes}'::text[] AS patient_improved_yes,
   doc #>> '{fields,group_improved,patient_improved_no}'::text[] AS patient_improved_no,
   doc #>> '{fields,group_referral_followup,g_patient_health_facility_visit}'::text[] AS g_patient_health_facility_visit,
   doc #>> '{fields,group_referral_followup,no_facility_visit}'::text[] AS no_facility_visit,
   doc #>> '{fields,group_better,g_patient_better}'::text[] AS g_patient_better,
   doc #>> '{fields,group_better,patient_better_yes}'::text[] AS patient_better_yes,
   doc #>> '{fields,group_better,patient_better_no}'::text[] AS patient_better_no,
   ''::text AS "meta/instanceID",
   doc ->> '_id'::text AS xmlforms_uuid,
   to_timestamp((NULLIF(doc ->> 'reported_date', '')::bigint / 1000)::double precision) AS reported
  FROM {{ ref("couchdb") }} form
    JOIN {{ ref("form_metadata") }} fm ON fm.uuid = (doc ->> '_id'::text)
    LEFT JOIN {{ ref("couchdb") }} patient ON (patient.doc ->> '_id'::text) = (doc #>> '{fields,patient_id}'::text[])
 WHERE doc->>'type' = 'data_record' AND (doc ->> 'form'::text) = 'assessment_follow_up'::text